---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firewall-controller-manager
  labels:
    app: firewall-controller-manager
spec:
  selector:
    matchLabels:
      app: firewall-controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        app: firewall-controller-manager
      annotations:
    spec:
      serviceAccountName: firewall-controller-manager
      containers:
      - name: firewall-controller-manager
        image: ghcr.io/metal-stack/firewall-controller-manager:initial-firewall-ruleset
        imagePullPolicy: Always
        args:
          - -cert-dir=/certs
          - -log-level=info
          - -seed-api-url=https://kubernetes
          # - -shoot-api-url={{ firewall_controller_manager_shoot_api_url }}
          # - -internal-shoot-api-url=https://kube-apiserver
          # - -cluster-id={{ firewall_controller_manager_cluster_id }}
          - -enable-leader-election
          - -metal-api-url=$(METAL_API_URL)
          - -shoot-kubeconfig-secret-name=none
          - -shoot-token-secret-name=none
          - -ssh-key-secret-name=none
          - -ssh-key-secret-namespace=none
          # - -shoot-token-path=/token
        env:
          - name: METAL_AUTH_HMAC
            value: metal-admin
          #   valueFrom:
          #     secretKeyRef:
          #       name: capms-controller-manager-config
          #       key: api-hmac
          - name: METAL_API_URL
            valueFrom:
              secretKeyRef:
                name: capms-controller-manager-config
                key: api-url
        livenessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: "RuntimeDefault"
        volumeMounts:
        - name: webhook-certs
          mountPath: "/certs"
          readOnly: true
        - name: token-dir
          mountPath: "/token"
        resources:
          limits:
            cpu: 400m
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 20Mi
      volumes:
      - name: webhook-certs
        secret:
          secretName: capms-firewall-controller-manager-webhooks
      - name: token-dir
        emptyDir: {}
