---
namespace: capms-system
namePrefix: capms-

resources:
- bases/firewall.metal-stack.io_firewalldeployments.yaml
- bases/firewall.metal-stack.io_firewallmonitors.yaml
- bases/firewall.metal-stack.io_firewallsets.yaml
- bases/firewall.metal-stack.io_firewalls.yaml
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment.yaml
- mutatingwebhookconfiguration.yaml
- sa.yaml
- service.yaml
- validatingwebhookconfiguration.yaml
- webhook-certs.yaml

labels:
- includeSelectors: true
  pairs:
    clusterctl.cluster.x-k8s.io/move: ""
    # or cluster.x-k8s.io/provider: infrastructure-metal-stack?

patches:

configurations:
- kustomizeconfig.yaml

replacements:
 - source:
     kind: Certificate
     group: cert-manager.io
     version: v1
     name: capms-firewall-controller-manager-webhooks
     fieldPath: .metadata.namespace
   targets:
     - select:
         kind: ValidatingWebhookConfiguration
         name: capms-firewall-controller-manager
       fieldPaths:
         - .metadata.annotations.[cert-manager.io/inject-ca-from]
       options:
         delimiter: '/'
         index: 0
         create: true

 - source:
     kind: Certificate
     group: cert-manager.io
     version: v1
     name: capms-firewall-controller-manager-webhooks
     fieldPath: .metadata.name
   targets:
     - select:
         kind: ValidatingWebhookConfiguration
         name: capms-firewall-controller-manager
       fieldPaths:
         - .metadata.annotations.[cert-manager.io/inject-ca-from]
       options:
         delimiter: '/'
         index: 1
         create: true

 - source:
     kind: Certificate
     group: cert-manager.io
     version: v1
     name: capms-firewall-controller-manager-webhooks
     fieldPath: .metadata.namespace
   targets:
     - select:
         kind: MutatingWebhookConfiguration
         name: capms-firewall-controller-manager
       fieldPaths:
         - .metadata.annotations.[cert-manager.io/inject-ca-from]
       options:
         delimiter: '/'
         index: 0
         create: true

 - source:
     kind: Certificate
     group: cert-manager.io
     version: v1
     name: capms-firewall-controller-manager-webhooks
     fieldPath: .metadata.name
   targets:
     - select:
         kind: MutatingWebhookConfiguration
         name: capms-firewall-controller-manager
       fieldPaths:
         - .metadata.annotations.[cert-manager.io/inject-ca-from]
       options:
         delimiter: '/'
         index: 1
         create: true

 - source:
     kind: Service
     version: v1
     name: firewall-controller-manager
     fieldPath: .metadata.name
   targets:
     - select:
         kind: Certificate
         group: cert-manager.io
         version: v1
         name: firewall-controller-manager-webhooks
       fieldPaths:
         - .spec.dnsNames.0
         - .spec.dnsNames.1
       options:
         delimiter: '.'
         index: 0
         create: true

 - source:
     kind: Service
     version: v1
     name: firewall-controller-manager
     fieldPath: .metadata.namespace
   targets:
     - select:
         kind: Certificate
         group: cert-manager.io
         version: v1
         name: firewall-controller-manager-webhooks
       fieldPaths:
         - .spec.dnsNames.0
         - .spec.dnsNames.1
       options:
         delimiter: '.'
         index: 1
         create: true
