---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: firewall-controller-manager
rules:
- apiGroups:
  - firewall.metal-stack.io
  resources:
  - firewalls
  - firewalls/status
  - firewallsets
  - firewallsets/status
  - firewalldeployments
  - firewalldeployments/status
  - firewallmonitors
  - firewallmonitors/status
  verbs:
  - '*'
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
- apiGroups:
  - ""
  resources:
  - secrets
  - serviceaccounts
  - namespaces
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  - clusterroles
  - clusterrolebindings
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
- apiGroups:
  - extensions.gardener.cloud
  resources:
  - infrastructures
  - extensions
  verbs:
  - get
- apiGroups:
  - extensions.gardener.cloud
  resources:
  - infrastructures/status
  verbs:
  - patch
- apiGroups:
  - extensions.gardener.cloud
  resources:
  - extensions
  verbs:
  - update
