---
apiVersion: v1
kind: Secret
metadata:
  name: firewall-controller-manager-certs
data:
  ca.crt: {{ firewall_controller_manager_ca | b64encode }}
  tls.crt:  {{ firewall_controller_manager_cert | b64encode }}
  tls.key: {{ firewall_controller_manager_cert_key | b64encode }}
