---
apiVersion: v1
kind: Service
metadata:
  name: firewall-controller-manager
  namespace: {{ firewall_controller_manager_namespace }}
  labels:
    app: firewall-controller-manager
spec:
  type: ClusterIP
  ports:
  - name: webhooks
    port: 9443
    protocol: TCP
  - name: metrics
    port: 2112
    protocol: TCP
  selector:
    app: firewall-controller-manager
