---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: firewall-controller-manager-{{ firewall_controller_manager_namespace }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: {{ firewall_controller_manager_ca | b64encode }}
    service:
      name: firewall-controller-manager
      namespace: {{ firewall_controller_manager_namespace }}
      port: 9443
      path: /validate-firewall-metal-stack-io-v2-firewall
  failurePolicy: Fail
  name: firewall.metal-stack.io
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: {{ firewall_controller_manager_namespace }}
  rules:
  - apiGroups:
    - firewall.metal-stack.io
    apiVersions:
    - v2
    operations:
    - CREATE
    - UPDATE
    resources:
    - firewalls
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: {{ firewall_controller_manager_ca | b64encode }}
    service:
      name: firewall-controller-manager
      namespace: {{ firewall_controller_manager_namespace }}
      port: 9443
      path: /validate-firewall-metal-stack-io-v2-firewallset
  failurePolicy: Fail
  name: firewallset.metal-stack.io
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: {{ firewall_controller_manager_namespace }}
  rules:
  - apiGroups:
    - firewall.metal-stack.io
    apiVersions:
    - v2
    operations:
    - CREATE
    - UPDATE
    resources:
    - firewallsets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: {{ firewall_controller_manager_ca | b64encode }}
    service:
      name: firewall-controller-manager
      namespace: {{ firewall_controller_manager_namespace }}
      port: 9443
      path: /validate-firewall-metal-stack-io-v2-firewalldeployment
  failurePolicy: Fail
  name: firewalldeployment.metal-stack.io
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: {{ firewall_controller_manager_namespace }}
  rules:
  - apiGroups:
    - firewall.metal-stack.io
    apiVersions:
    - v2
    operations:
    - CREATE
    - UPDATE
    resources:
    - firewalldeployments
  sideEffects: None
