---
services:
  clusterctl:
    image: registry.k8s.io/cluster-api/clusterctl:v1.12.3
    environment:
      - EXP_KUBEADM_BOOTSTRAP_FORMAT_IGNITION=true
      - METAL_API_HMAC=${METAL_API_HMAC}
      - METAL_API_URL=${METAL_API_URL}
      - METAL_API_HMAC_AUTH_TYPE=${METAL_API_HMAC_AUTH_TYPE}
      - CLUSTER_NAME=${CLUSTER_NAME}
      - TENANT_NAMESPACE=${TENANT_NAMESPACE}
      - KUBERNETES_VERSION=${KUBERNETES_VERSION}
      - CONTROL_PLANE_IP=${CONTROL_PLANE_IP}
      - PODS_CIDR=${PODS_CIDR}
      - SERVICES_CIDR=${SERVICES_CIDR}
      - METAL_PARTITION=${METAL_PARTITION}
      - METAL_PROJECT_ID=${METAL_PROJECT_ID}
      - CONTROL_PLANE_MACHINE_IMAGE=${CONTROL_PLANE_MACHINE_IMAGE}
      - CONTROL_PLANE_MACHINE_SIZE=${CONTROL_PLANE_MACHINE_SIZE}
      - WORKER_MACHINE_IMAGE=${WORKER_MACHINE_IMAGE}
      - WORKER_MACHINE_SIZE=${WORKER_MACHINE_SIZE}
      - FIREWALL_MACHINE_IMAGE=${FIREWALL_MACHINE_IMAGE}
      - FIREWALL_MACHINE_SIZE=${FIREWALL_MACHINE_SIZE}
      - METAL_NODE_NETWORK_ID=${METAL_NODE_NETWORK_ID}
      - FIREWALL_EXTERNAL_NETWORKS=${FIREWALL_EXTERNAL_NETWORKS}
    volumes:
      - ../config/clusterctl-templates:/templates:ro
