---
services:
  clusterctl:
    image: registry.k8s.io/cluster-api/clusterctl:v1.12.3
    environment:
      - TENANT_NAMESPACE=${TENANT_NAMESPACE}
      - PODS_CIDR=${PODS_CIDR}
      - SERVICES_CIDR=${SERVICES_CIDR}
      - METAL_NODE_NETWORK_ID=${METAL_NODE_NETWORK_ID}
