---
services:
  capi:
    image: ghcr.io/metal-stack/metal-deployment-base:${DEPLOYMENT_BASE_IMAGE_TAG}
    container_name: capi
    volumes:
      - ..:/deploy
      # for developing role dependencies
      # TODO: make this a switch
      # - ${HOME}/.ansible/roles/ansible-common:/root/.ansible/roles/ansible-common:ro
      # - ${HOME}/.ansible/roles/metal-roles:/root/.ansible/roles/metal-roles:ro
      # - ${HOME}/.ansible/roles/metal-ansible-modules:/root/.ansible/roles/metal-ansible-modules:ro
      # - ${HOME}/git/github.com/metal-stack/helm-charts:/helm-charts:ro
    environment:
      - ANSIBLE_CONFIG=ansible.cfg
      - KUBECONFIG=/deploy/capi-lab/mini-lab/.kubeconfig
      - K8S_AUTH_KUBECONFIG=/deploy/capi-lab/mini-lab/.kubeconfig
    env_file:
      - .env
    network_mode: host
    working_dir: /deploy/capi-lab
    entrypoint:
      - /bin/bash
      - -ce
      - |
        ansible-playbook -i inventory.yaml obtain_role_requirements.yaml
        ansible-galaxy install --ignore-errors -r requirements.yaml
        ansible-playbook -i inventory.yaml deploy.yaml --extra-vars "@.extra_vars.yaml"
