---
services:
  clusterctl:
    environment:
      - METAL_API_HMAC=${METAL_API_HMAC}
      - METAL_API_URL=${METAL_API_URL}
      - METAL_API_HMAC_AUTH_TYPE=${METAL_API_HMAC_AUTH_TYPE}
    volumes:
      - ./clusterctl-kamaji.yaml:/root/.config/cluster-api/clusterctl.yaml:ro
