---
- name: deploy cluster-api-provider-metal-stack
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    setup_yaml:
      - url: https://raw.githubusercontent.com/metal-stack/releases/develop/release.yaml
        meta_var: metal_stack_release
  roles:
    - name: ansible-common
    - name: metal-roles
    - name: prometheus
    - name: firewall-controller-manager
      vars:
        firewall_controller_manager_namespace: capms-system
        firewall_controller_manager_ca: "{{ lookup('file', playbook_dir + '/fcm-certs/ca.pem') }}"
        firewall_controller_manager_cert: "{{ lookup('file', playbook_dir + '/fcm-certs/tls.crt') }}"
        firewall_controller_manager_cert_key: "{{ lookup('file', playbook_dir + '/fcm-certs/tls.key') }}"
    - name: cluster-api
