---
- name: deploy cluster-api-provider-metal-stack
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    setup_yaml:
      - url: https://raw.githubusercontent.com/metal-stack/releases/develop/release.yaml
        meta_var: metal_stack_release
  roles:
    - name: ansible-common
    - name: metal-roles
    - name: prometheus
    - name: cluster-api
