---
- name: provide requirements.yaml
  hosts: capi
  connection: local
  gather_facts: false
  tasks:
    - name: include mini-lab release vars
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/mini-lab/inventories/group_vars/all/images.yaml"

    - name: download metal-stack release vector
      uri:
        url: "https://raw.githubusercontent.com/metal-stack/releases/{{ metal_stack_release_version }}/release.yaml"
        return_content: yes
      register: metal_stack_release_vector

    - name: write requirements.yaml from release vector
      copy:
        dest: "{{ playbook_dir }}/requirements.yaml"
        content: |
          {% for role_name, role_params in (metal_stack_release_vector.content | from_yaml).get('ansible-roles').items() %}
          - src: {{ role_params.get('repository') }}
            name: {{ role_name }}
            version: {{ hostvars[inventory_hostname][role_name | lower | replace('-', '_') + '_version'] | default(role_params.get('version'), true) }}
          {% endfor %}
