- src: https://github.com/metal-stack/ansible-common
  name: ansible-common
  version: v0.6.12
- src: https://github.com/metal-stack/metal-ansible-modules
  name: metal-ansible-modules
  version: v0.2.9
- src: https://github.com/metal-stack/metal-roles
  name: metal-roles
  version: v0.14.2
