---
- name: Create namespace
  k8s:
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ prometheus_namespace }}"
        labels:
          name: "{{ prometheus_namespace }}"

- name: Deploy Prometheus
  include_role:
    name: ansible-common/roles/helm-chart
  vars:
    helm_chart: kube-prometheus-stack
    helm_repo: https://prometheus-community.github.io/helm-charts
    helm_force: false
    helm_release_name: kube-prometheus-stack
    helm_target_namespace: "{{ prometheus_namespace }}"
    helm_chart_version: "{{ prometheus_helm_chart_version }}"
    # helm_value_file_template: values.yaml
