---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capi-metal-stack-clusters
  labels:
    cluster.x-k8s.io/aggregate-to-manager: "true"
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - metalstackclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
