apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: calico-cni
spec:
  clusterSelector:
    matchLabels:
      cluster.metal-stack.io/cni: calico
  releaseName: calico
  repoURL: https://docs.tigera.io/calico/charts
  chartName: tigera-operator
  namespace: kube-system
  version: v3.28.3
  valuesTemplate: |
    installation:
      enabled: true

      calicoNetwork:
        bgp: Disabled
        ipPools:
        - name: default-ipv4-ippool
          blockSize: 26
          cidr: 10.240.0.0/12
          encapsulation: None
        mtu: 1440
      cni:
        ipam:
          type: HostLocal
        type: Calico

    goldmane:
      enabled: false

    whisker:
      enabled: false
