---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-metal-stack
  name: metal-stack-controller-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-metal-stack
  name: metal-stack-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election-role
subjects:
- kind: ServiceAccount
  name: metal-stack-controller-manager
  namespace: {{ cluster_api_provider_metal_stack_namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-metal-stack
  name: metal-stack-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-role
subjects:
- kind: ServiceAccount
  name: metal-stack-controller-manager
  namespace: {{ cluster_api_provider_metal_stack_namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: metal-api
data:
  api-url: "{{ cluster_api_provider_metal_stack_metal_api_url | b64encode }}"
  api-hmac: "{{ cluster_api_provider_metal_stack_metal_api_hmac | b64encode }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metal-stack-controller-manager
  labels:
    control-plane: metal-stack-controller-manager
    app.kubernetes.io/name: cluster-api-provider-metal-stack
spec:
  selector:
    matchLabels:
      control-plane: metal-stack-controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: metal-stack-controller-manager
    spec:
      serviceAccountName: metal-stack-controller-manager
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /manager
        args:
          - --leader-elect
          - --health-probe-bind-address=:8081
        image: "{{ cluster_api_provider_metal_stack_controller_image_name }}:{{ cluster_api_provider_metal_stack_controller_image_tag }}"
        imagePullPolicy: IfNotPresent
        name: manager
        env:
        - name: METAL_API_URL
          valueFrom:
            secretKeyRef:
              name: metal-api
              key: api-url
        - name: METAL_API_HMAC
          valueFrom:
            secretKeyRef:
              name: metal-api
              key: api-hmac
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      terminationGracePeriodSeconds: 10
