---
name: Release Drafter Action

on:
  push:
    branches:
      - main
      - fix-release-drafts
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Draft Release
        id: draft_release
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: install kustomize
        run: |
          make kustomize
      - name: generate release artifacts
        env:
          IMG_TAG: ${{ github.ref_name }}
          RELEASE_DIR: .release
        run: |
          make release-manifests

      - name: Attach release manifests
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ steps.draft_release.outputs.resolved_version }}
          tag_name: ${{ steps.draft_release.outputs.tag_name }}
          draft: true
          fail_on_unmatched_files: true
          files: .release/*
